# Generated by Django 5.2.5 on 2025-10-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='sample',
            new_name='sample_file',
        ),
    ]
